FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true
ENV HOSTNAME=0.0.0.0
ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev"]