# ============================================
# Development Dockerfile for Next.js
# ============================================
ARG NODE_VERSION=20-alpine

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

COPY package*.json  ./

RUN npm ci 

COPY . .

ENV WATCHPACK_POLLING=true
ENV HOSTNAME="0.0.0.0"
ENV API_URL_BACK="http://localhost:8000/"

RUN chown -R node:node /app
USER node

EXPOSE 3000

CMD ["npm", "run", "dev"]