services:
  nextjs-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: nextjs-sample:dev
    container_name: nextjs-sample-dev
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /src/app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json

  fastapi-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: fastapi-sample:dev
    container_name: fastapi-sample-dev
    ports:
      - "8000:8000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
    depends_on:
      - mysql
    networks:
      - ollama-docker

  mysql:
    image: mysql:8
    container_name: mysql-dev
    environment:
      MYSQL_DATABASE: job_pilot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - ollama-docker

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-dev
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql

  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: docker.io/ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]

networks:
  ollama-docker:
    external: false