FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

RUN echo "DATABASE_URL=mysql+pymysql://user:password@mysql:3306/job_pilot" > .env && \
    echo "MODEL_OLLAMA=qwen2.5:7b" >> .env

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]